### ISSUE TITLE
[bug] Auto-ingest not working

### ISSUE THREAD

**Issue by mmonseurs** [crocodilestick/Calibre-Web-Automated#106] opened 2024-10-09 20:02 UTC
**Describe the bug**
Placing a book in the ingest folder does not add it to the library, even though it is deleted and the logs say it was added.

**To Reproduce**
1. Place book in ingest folder
2. Wait
3. See that the file is deleted but no entry in the library

**Expected behavior**
Book is added to the library

**Configuration(please complete the following information):**
 - OS: Ubuntu Server (22.04 LTS)
 - Hardware: x86 server / minipc
 - Version: V2.0.1 

**Additional context**
Had this issue before, but it concerned incorrect mapping of folders. Currently my library is mapped to calibre-library. My compose file:

services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1002
    volumes:
      - /home/max/calibre-web/config:/config
      - /media/usenet/cwa-book-ingest:/cwa-book-ingest
      - /media/books:/calibre-library
    ports:
      - 8085:8083
    networks:
      - infra_net
    restart: unless-stopped

Logs:
============== STARTING NEW BOOK DETECTOR ==============
========== STARTING BOOKS-TO-PROCESS DETECTOR ==========
========== STARTING METADATA CHANGE DETECTOR ===========
[metadata-change-detector]: Watching folder: /app/calibre-web-automated/metadata_change_logs
Setting up watches.
Watches established.
[new-book-detector]: Watching folder: /app/calibre-web-automated/cwa-import
[books-to-process]: Watching folder: /cwa-book-ingest
Setting up watches.  Beware: since -r was given, this may take a while!
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
Watches established.
[ls.io-init] done.
[books-to-process]: New files detected - /cwa-book-ingest/forwearemany.epub
[new-book-detector]: New file detected: /app/calibre-web-automated/cwa-import/forwearemany.epub
./run: line 22: /usr/bin/calibredb: No such file or directory
[new-book-detector] Added /app/calibre-web-automated/cwa-import/forwearemany.epub to Calibre database
[new-book-detector]: Removing /app/calibre-web-automated/cwa-import/forwearemany.epub from import folder...
find: cannot delete ‘/cwa-book-ingest/’: Device or resource busy
[new-book-processor]: Found  epub file in ingest folder.
[new-book-processor]: Moving epub file to the CWA import folder...
[new-book-processor]: Moving /cwa-book-ingest/forwearemany.epub...
[new-book-detector]: /app/calibre-web-automated/cwa-import/forwearemany.epub successfully moved/converted, the Ingest Folder has been emptied and is ready
[books-to-process]: New files successfully moved/converted, the Ingest Folder has been emptied and is ready to go again.

**Comment by jmarmstrong1207** [comment] 2024-10-14 03:37
Could you check if you are transferring the files into cwa-ingest with those files being owned by your user, not root? if they're owned by root, it doesn't work at least for me

**Comment by jmarmstrong1207** [comment] 2024-10-14 05:41
I also have added a new release v2.1.0-dev-2 deprecating auto ingestion, and instead having the user press "Ingest Books" as it's not 100% reliable. If it still doesn't work, try using that version's image:
`jmarmstrong1207/calibre-web-automated:v2.1.0-dev-2`

https://github.com/crocodilestick/Calibre-Web-Automated/releases

**Comment by mmonseurs** [comment] 2024-10-14 13:48
Files are owned by me (max:max), calibre container is run as max:media. 

I tried your dev image but that didn't work either. Logs:

      d8"     `Y8             IP'`Yb       IP'`Yb                                 Yb, `88     88     d8'          IP'`Yb               
     d8'   8b  d8             I8  8I  gg   I8  8I                                  `"  88     88     88           I8  8I               
    ,8I    "Y88P'             I8  8'  ""   I8  8'                                      88     88     88           I8  8'               
    I8'             ,gggg,gg  I8 dP   gg   I8 dP        ,gggggg,   ,ggg,   aaaaaaaa    88     88     88   ,ggg,   I8 dP                
    d8             dP"  "Y8I  I8dP    88   I8dP   88gg  dP""""8I  i8" "8i  """"""""    88     88     88  i8" "8i  I8dP   88gg          
    Y8,           i8'    ,8I  I8P     88   I8P    8I   ,8'    8I  I8, ,8I              Y8    ,88,    8P  I8, ,8I  I8P    8I            
    `Yba,,_____, ,d8,   ,d8b,,d8b,_ _,88,_,d8b,  ,8I  ,dP     Y8, `YbadP'               Yb,,d8""8b,,dP   `YbadP' ,d8b,  ,8I            
      `"Y8888888 P"Y8888P"`Y88P'"Y888P""Y88P'"Y88P"'  8P      `Y8888P"Y888               "88"    "88"   888P"Y8888P'"Y88P"'            
                         █████╗ ██╗   ██╗████████╗ ██████╗ ███╗   ███╗ █████╗ ████████╗███████╗██████╗ 
                        ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗████╗ ████║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗
                        ███████║██║   ██║   ██║   ██║   ██║██╔████╔██║███████║   ██║   █████╗  ██║  ██║
                        ██╔══██║██║   ██║   ██║   ██║   ██║██║╚██╔╝██║██╔══██║   ██║   ██╔══╝  ██║  ██║
                        ██║  ██║╚██████╔╝   ██║   ╚██████╔╝██║ ╚═╝ ██║██║  ██║   ██║   ███████╗██████╔╝
                        ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝ 
                             ~~~ Based on images from linuxserver.io & Calibre-Web by janeczku ~~~
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1002
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[cwa-init-remove-locks] Checking for leftover lock files from prvious instance...
[cwa-set-perms] Recursively setting ownership of everything in /config, /calibre-library, /app/calibre-web-automated to abc:abc...
[cwa-init-remove-locks] No leftover lock files to remove. Ending service...
[cwa-set-perms] Successfully set permissions for '/config'!
[cwa-set-perms] Successfully set permissions for '/calibre-library'!
[cwa-set-perms] Successfully set permissions for '/app/calibre-web-automated'!
[cwa-set-perms] Ending service...
[auto-library]: Multiple metadata.db files found in library directory:
    - /calibre-library/metadata.db | Size: 532480
    - /calibre-library/Calibre Library/metadata.db | Size: 397312
[auto-library]: Automatically mounting the largest database using the following db file - /calibre-library/metadata.db ...
[auto-library]: If this is unwanted, please ensure only 1 metadata.db file / only your desired Calibre Database exists in '/calibre-library', then restart the container
[auto-library] Updating dirs.json with new library location...
[auto-library]: Updating Settings Database with library location...
[auto-library] Library location successfully set to: /calibre-library
========== STARTING METADATA CHANGE DETECTOR ===========
========== STARTING CWA-INGEST SERVICE ==========
[cwa-ingest-service]: Watching folder: /cwa-book-ingest
[metadata-change-detector]: Watching folder: /app/calibre-web-automated/metadata_change_logs
Setting up watches.  Beware: since -r was given, this may take a while!
Setting up watches.
Watches established.
Watches established.
[ls.io-init] done.
[cwa-ingest-service]: New files detected - /cwa-book-ingest/fwam.epub
[ingest-processor]: No conversion needed for fwam.epub, importing now...
[ingest-processor]: Importing new epub to CWA...
Traceback (most recent call last):
  File "/app/calibre-web-automated/scripts/ingest-processor.py", line 189, in <module>
    main()
  File "/app/calibre-web-automated/scripts/ingest-processor.py", line 182, in main
    nbp.add_book_to_library(filepath)
  File "/app/calibre-web-automated/scripts/ingest-processor.py", line 123, in add_book_to_library
    subprocess.run(["calibredb", "add", book_path, f"--library-path={self.library_dir}"], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'calibredb'
[cwa-ingest-service]: New files successfully moved/converted, the Ingest Folder has been emptied and is ready to go again.
['fwam.epub']
[ingest-processor]: No conversion needed for fwam.epub, importing now...
Traceback (most recent call last):
  File "/app/calibre-web-automated/scripts/ingest-processor.py", line 189, in <module>
[ingest-processor]: Importing new epub to CWA...
    main()
  File "/app/calibre-web-automated/scripts/ingest-processor.py", line 162, in main
    main(f)
  File "/app/calibre-web-automated/scripts/ingest-processor.py", line 182, in main
    nbp.add_book_to_library(filepath)
  File "/app/calibre-web-automated/scripts/ingest-processor.py", line 123, in add_book_to_library
    subprocess.run(["calibredb", "add", book_path, f"--library-path={self.library_dir}"], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'calibredb'

**Comment by crocodilestick** [comment] 2024-11-01 22:56
Hey @mmonseurs, the issue is in your compose file. You are missing the following environment variable:

DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0

**Closed by crocodilestick** 2024-11-01 22:56 UTC
Labels: bug

**Comment by mmonseurs** [comment] 2024-11-03 09:22
Nice, I'll give this a shot tonight, thanks for the help!

**Comment by netsrot303** [comment] 2025-03-18 12:38
I'm sorry to open this issue again, but unfortunately the installation on my Synology 1815plus did not work. I get this error when creating the stack: 

"[universal-calibre-setup] Calibre setup was unsuccessful, 'calibre_postinstall' encountered an error. Exiting now..."

When I push ebooks into the ingest directory I get this error:

"[Errno 2] No such file or directory: 'calibredb'".

Do you have a solution?
The solution with the Docker mods 
DOCKER_MODS=lscr.io/linuxserver/mods:universal-calibre-v7.16.0
didn't work either.
